include("${CMAKE_CURRENT_LIST_DIR}/../cmake/HuxerUIExamples.cmake")

add_subdirectory(counter)
add_subdirectory(ui_gallery)
add_subdirectory(dynamic_list)
add_subdirectory(scroll_view)
add_subdirectory(virtual_list)
add_subdirectory(horizontal_virtual_list)
add_subdirectory(virtual_grid)
add_subdirectory(custom_event)
add_subdirectory(presentation)
add_subdirectory(theme)
add_subdirectory(tabs)
add_subdirectory(environment)
add_subdirectory(canvas)
add_subdirectory(image)
